### PR TITLE
Added contributor to DESCRIPTION

### PR DESCRIPTION
**Pull request by GerardWalsh**

### CODE REVIEW

**Comment by datawookie** [comment]
Thanks, Gary.

One minor request. Can you please change the anchor text as follows: "[grant access](URL GOES HERE) to less secure apps".

Also be sure to have a period at the end of the sentence.

**Comment by datawookie** [comment]
Don't worry. I did it. Couldn't delay. Want to write blog post.

**Comment by GerardWalsh** [comment]
Sorry, this comes to my personal email - have changed my primary email to
be exegetic.biz account

**Comment by datawookie** [comment]
No problem. Probably a good plan because most of your Githubbing will be work related (for the moment anyway!).

**Pull request merged**
