### PR TITLE
add option to set distinct HELO/EHLO domain

### PR DESCRIPTION
**Pull request by Rdataflow**
some environments need a specific HELO client.domain.fqdn
details see https://everything.curl.dev/usingcurl/smtp#the-smtp-url
i.e. `curl smtp://mail.example.com/client.example.com`

### CODE REVIEW

**Comment by datawookie** [comment]
Thanks, @Rdataflow! I've made some minor tweaks and merged the changes. Your contribution acknowledged in `NEWS.md`.

**Comment by Rdataflow** [comment]
@datawookie thx!

**Comment by Rdataflow** [comment]
@datawookie when do you think this new release 0.4.12 will land in CRAN?

**Comment by datawookie** [comment]
@Rdataflow it's been submitted to CRAN. Should be there in the next 24 hours or so.

**Comment by Rdataflow** [comment]
@datawookie you are really fast, it's there already. - NB: only [gh-pages](https://github.com/datawookie/emayili/tree/gh-pages) is out of sync and could have an update to 0.4.12... big thx!

**Comment by datawookie** [comment]
Thanks. I've updated the documentation too.

**Pull request closed without merging**
