### PR TITLE
Using curl::send_mail

### PR DESCRIPTION
**Pull request by datawookie**

### CODE REVIEW

**Comment by okhoma** [comment]
Hi @datawookie - when do you plan to upload the new version to CRAN?

**Comment by datawookie** [comment]
I'm waiting to hear back from a number of people about pending issues. But if they don't get back to me this afternoon then I'll upload a new version anyway. Thanks for prompting me!

**Comment by datawookie** [comment]
Hi @okhoma, I've just submitted {emayili}-0.4.0 to CRAN. Best regards, Andrew.

**Comment by okhoma** [comment]
Thank you, all looks good

**Pull request merged**
