### PR TITLE
Allow any UTF-8 characters in attachment filenames

### PR DESCRIPTION
**Pull request by hallmeier**
`emayili` always embeds filenames in the MIME header like this: `filename="<filename>"`. There are certain restrictions to the set of characters that can appear in such filenames. First of all, they all have to be ASCII characters. So using a filename like "señor.csv" evokes undefined behavior. For me, the content of the csv would always display in the base64 encoded form. [RFC2231](https://tools.ietf.org/html/rfc2231) provides a standard for how non-ASCII characters in MIME header fields can be encoded. In this case the header part would be: `filename*=utf-8''se%C3%B1or.csv`. Through exhaustive testing on a Unix machine (since Windows won't even allow some characters in filenames) I found that ASCII control characters, double quotation marks and backslashes also have to be encoded. In case RFC2231 is used, " ", "%" and ";" are added to this list.

This pull request adds a function to perform the appropiate formatting of parameter values in MIME headers. It is applied to the "name" and "filename" header fields. This allows for any possible UTF-8 characters in attachment filenames.

It is assumed that the input strings are always in UTF-8 encoding. This should hold true as `basename(path)` returns them that way.

### CODE REVIEW

**Comment by hallmeier** [comment]
So how about it? It's been half a year without a response. It would be great not to have to monkey patch `emayili` to send out attachments with arbitrary filenames.

The failed CI should not be my fault. Some login got denied.

**Comment by datawookie** [comment]
Hi Philipp Hallmeier (@hallmeier),

Thanks for logging this issue. I think that it's a great suggestion.

> The failed CI should not be my fault.

Definitely not. Don't believe that anybody suggested that you were responsible.

> So how about it? It's been half a year without a response.

I'm wondering: do I know you? Because you address me like I work for you or are somehow answerable to you. As a general principle, I find that I have greater success when I am polite (like starting a message with a suitable salutation).

Best regards, Andrew.

**Comment by datawookie** [comment]
Hi Phillipp,

Merged and added simple tests on `parameter_value_encode()`.

Also the CI issue didn't turn out to be a login problem. An updated R package had additional `apt` dependencies which needed to be included.

These changes have been merged into the `master` branch and the version has been bumped to 0.4.5. CI checks are passing.

Best regards, Andrew.

**Comment by hallmeier** [comment]
Hi Andrew,

thanks for accepting the pull request.

I added the comment about the CI in case the PR wasn't responded to because of the failing CI.

No, we do not know each other and I did not mean to be impolite. Sorry if it sounded that way. I just wanted to state the reason I am commenting on this PR again. Didn't want to be impatient, but as other development in this project took place, I wanted at least a short answer whether this PR would be addressed or whether there was something wrong with it.

Best regards, Philipp

**Comment by datawookie** [comment]
No worries. And thanks for your contribution. This is, I'm sure, going to be seriously useful to other users.

**Pull request merged**
