### PR TITLE
Small changes

### PR DESCRIPTION
**Pull request by abichat**
Global informations about less secure apps
Change `dplyr` calls to `magrittr` call (to remove dependancy)

### CODE REVIEW

**Comment by datawookie** [comment]
Hi @abichat, thanks for your contributions. I have merged them into the `dev` branch. I'll do some local testing and then merge into `master`. Can I add you as a contributor in `DESCRIPTION`?

**Comment by datawookie** [comment]
Changes merged into `master`. Let me know about adding you as contributor.

**Comment by abichat** [comment]
Yes, thanks for your proposal, I'm happy to contribute to this promising package :) 
`person(given = "Antoine", family = "Bichat", role = "ctb, email = "a.bichat@yahoo.fr", comment = c(ORCID = "0000-0001-6599-7081"))`

**Comment by datawookie** [comment]
Done!

**Pull request merged**
